export default {
  // loading recipes
  FETCH_ALL_RECIPES: 'FETCH_ALL_RECIPES',
  SORT_BY_ALPHA: 'SORT_BY_ALPHA',
  SORT_BY_CATEGORY: 'SORT_BY_CATEGORY',
  SORT_BY_SUBCATEGORY: 'SORT_BY_SUBCATEGORY',
  UPDATE_BREADCRUMBS: 'UPDATE_BREADCRUMBS',
  // filtering recipes
  QUERY_INPUT: 'QUERY_INPUT',
  REMOVE_FILTERED_RECIPES: 'REMOVE_FILTERED_RECIPES',
  // adding and editing recipes
  SET_CURRENT_RECIPE: 'SET_CURRENT_RECIPE'
}
